trigger:
  tags:
    include:
    - 'v*'

resources:
  repositories:
  - repository: templatesRepo
    type: git
    name: Stater/devops-pipelines

stages:
- stage: build and push docker image
  jobs:
  - template: /jobs/build/docker-image.yml@templatesRepo
    parameters:
      dockerFilePath: ./Dockerfile.standalone
      path: stater
      image: external-secrets-ntlm
        tag: ${{ parameters.tag }}
      buildArgs: "--build-arg GOPROXY=http://pr-art.europe.stater.corp/artifactory/gocenter"
